[package]
name = "bevy-suis"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = "0.14"
# bevy_mod_xr = { git = "https://github.com/awtterpip/bevy_oxr" }
bevy_mod_xr = { git = "https://github.com/awtterpip/bevy_oxr.git", rev = "c0be012b9dcc6a501a87aff9b7eafb3d886d8c9e"}

#schminput = { git = "https://github.com/Schmarni-Dev/schminput", features = [
#	"xr",
#], rev = "42a572a"}
schminput = { git = "https://github.com/MiniMinerX/schminput", features = [
	"xr",
], branch = "revision"}

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# bevy_mod_openxr = { git = "https://github.com/awtterpip/bevy_oxr" }
bevy_mod_openxr = { git = "https://github.com/awtterpip/bevy_oxr.git", rev = "c0be012b9dcc6a501a87aff9b7eafb3d886d8c9e"}

openxr = { version = "0.18.0", default-features = false }

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
