[package]
name = "bevy-suis"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = "0.14"
bevy_mod_xr = "0.1.1"
schminput = { version = "0.1.0", features = ["xr"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy_mod_openxr = "0.1.0"
openxr = { version = "0.18.0", default-features = false }

[dev-dependencies]
bevy_xr_utils = "0.1.0"

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
