[package]
name = "bevy-suis"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = []
xr = ["schminput/xr"]
raw_vulkan_init = []

[dependencies]
bevy = { workspace = true }
bevy_mod_xr = { workspace = true }
bevy_xr_utils = { workspace = true }
schminput = { git = "https://github.com/MiniMinerX/Schminput", branch = "bevy-0.19" }

[dev-dependencies]
bevy_mod_openxr = { workspace = true }
openxr = { workspace = true }
bevy = { workspace = true, default-features = true }

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[workspace]
members = ["bevy-suis-explicit-method-data"]

[workspace.dependencies]
bevy = { version = "0.19", default-features = false, features = [
	"bevy_asset",
	"bevy_camera",
	"bevy_color",
	"bevy_gizmos",
	"bevy_pbr",
	"zstd_rust",
] }

bevy_mod_openxr = { git = "https://github.com/MiniMinerX/bevy_oxr", branch = "olympus-loaded-default", package = "bevy_mod_openxr", version = "0.6.0" }
bevy_mod_xr   = { git = "https://github.com/MiniMinerX/bevy_oxr", branch = "olympus-loaded-default", package = "bevy_mod_xr",   version = "0.6.0" }
bevy_xr_utils = { git = "https://github.com/MiniMinerX/bevy_oxr", branch = "olympus-loaded-default", package = "bevy_xr_utils", version = "0.6.0" }

openxr = "0.21.1"
