[package]
name = "bevy-suis"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = []
xr = ["schminput/xr"]
raw_vulkan_init = ["schminput/raw_vulkan_init", "bevy_mod_openxr/raw_vulkan_init"]

[dependencies]
bevy = { version = "0.18.0", features = [
	"bevy_asset",
	"bevy_camera",
	"bevy_color",
	"bevy_gizmos",
	"bevy_pbr",
], default-features = false }
bevy_mod_xr = { git = "https://github.com/MiniMinerX/bevy_oxr.git", branch = "fix_dlss" }
schminput = { git = "https://github.com/MiniMinerX/Schminput", branch = "bevy-0.18" }

[dev-dependencies]
bevy_mod_openxr = { git = "https://github.com/MiniMinerX/bevy_oxr.git", branch = "fix_dlss" }
openxr = "0.21.1"
bevy = { version = "0.18.0", default-features = false }


[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[workspace]
members = ["bevy-suis-explicit-method-data"]
