[package]
name = "bevy-suis-explicit-method-data"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
schminput = { git = "https://github.com/Schmarni-Dev/schminput", features = [
	"xr",
], branch = "action_set_priorities" }
bevy-suis.path = ".."
